# Tests for DofGLMM — Poisson Chen-Stein influence df (issue #28)

@testitem "dof_glmm_poisson arithmetic kernel — Level-1 hand-computed" tags = [:level1] begin
    # Level-1 correctness gate (ADR-0003): supply pre-computed (y, η̂, ind, η̂_dec) and
    # verify the Chen-Stein sum formula ρ = Σᵢ yᵢ(η̂ᵢ - η̂ᵢ^{(-i)}) is reproduced exactly.
    # No model fitting or MixedModels dependency — pure arithmetic.
    #
    # Hand-computed expected value:
    #   y = [2.0, 0.0, 1.0, 3.0], nonzero at indices 1, 3, 4
    #   η̂  = [1.0, 0.5, 1.5, 2.0]
    #   η̂^{(-i)}_i = [0.9, 1.4, 1.8]  (refit eta at the decremented observation)
    #   ρ = 2*(1.0 - 0.9) + 1*(1.5 - 1.4) + 3*(2.0 - 1.8)
    #     = 0.2 + 0.1 + 0.6 = 0.9
    using cAIC: DofGLMM

    y = [2.0, 0.0, 1.0, 3.0]
    eta0 = [1.0, 0.5, 1.5, 2.0]
    ind = [1, 3, 4]
    eta_dec = [0.9, 1.4, 1.8]

    c = DofGLMM.PoissonInfluenceComponents(y, eta0, ind, eta_dec)
    ρ = DofGLMM.dof_glmm_poisson(c)
    @test ρ ≈ 0.9 atol = 1e-14
end

@testitem "dof_glmm_poisson arithmetic kernel — empty nonzero index returns 0.0" tags = [
    :level1
] begin
    # When every observation has yᵢ = 0, ind is empty and ρ = 0 (no contributions).
    using cAIC: DofGLMM

    y = [0.0, 0.0, 0.0]
    eta0 = [0.5, 0.3, 0.7]
    ind = Int[]
    eta_dec = Float64[]

    c = DofGLMM.PoissonInfluenceComponents(y, eta0, ind, eta_dec)
    @test DofGLMM.dof_glmm_poisson(c) === 0.0
end

@testitem "dof_glmm_poisson type stability — PoissonInfluenceComponents dispatch" tags = [
    :type_stability
] begin
    # dof_glmm_poisson(::PoissonInfluenceComponents{T}) must be @inferred for T = Float64
    # and T = Float32 (generic over the float type — CLAUDE §4).
    using cAIC: DofGLMM
    using Test: @inferred

    c64 = DofGLMM.PoissonInfluenceComponents(
        [2.0, 0.0, 1.0], [1.0, 0.5, 1.5], [1, 3], [0.9, 1.4]
    )
    @test @inferred(DofGLMM.dof_glmm_poisson(c64)) isa Float64

    c32 = DofGLMM.PoissonInfluenceComponents(
        Float32[2, 0, 1], Float32[1, 0.5, 1.5], [1, 3], Float32[0.9, 1.4]
    )
    @test @inferred(DofGLMM.dof_glmm_poisson(c32)) isa Float32
end

@testitem "dof_glmm_poisson Level-1 fixture — matches biasCorrectionPoisson components" tags = [
    :level1, :fixture
] begin
    # Level-1 correctness gate against the committed HDF5 fixture generated by
    # test/generate_fixtures_glmm_poisson.R (which sources cAIC4's biasCorrectionPoisson
    # and captures y, η̂, ind, η̂_dec from the refit loop, and the final ρ_ref).
    # No model fitting — pure arithmetic on pre-computed influence values.
    # Tolerance: rtol=1e-6, atol=1e-10 (Level-1 boundary; ADR-0003).
    using HDF5
    using cAIC: DofGLMM

    asscalar(x) = x isa AbstractArray ? only(x) : x

    fixture = joinpath(@__DIR__, "fixtures", "dof_glmm_poisson_level1.h5")
    @test isfile(fixture)

    h5open(fixture, "r") do f
        cases = filter(!=("meta"), keys(f))
        @test !isempty(cases)
        for name in cases
            g = f[name]
            haskey(g, "rho_ref") || error(
                "fixture case `$name` missing rho_ref — run generate_fixtures_glmm_poisson.R",
            )

            y = read(g["y"])
            eta0 = read(g["eta0"])
            ind = Vector{Int}(read(g["ind"]))
            eta_dec = read(g["eta_dec"])
            ρ_ref = asscalar(read(g["rho_ref"]))

            c = DofGLMM.PoissonInfluenceComponents(y, eta0, ind, eta_dec)
            ρ = DofGLMM.dof_glmm_poisson(c)
            @test ρ ≈ ρ_ref rtol = 1e-6 atol = 1e-10
        end
    end
end

@testitem "dof_glmm_poisson Level-2 fixture — full refit loop vs biasCorrectionPoisson" tags = [
    :level2, :fixture
] begin
    # Level-2 correctness gate: fit a Poisson GLMM in MixedModels.jl on the dataset
    # committed in the fixture, call dof_glmm_poisson(m), and compare to R's
    # biasCorrectionPoisson output. Tolerance derived from fit-discrepancy band (DECISIONS.md).
    using HDF5
    using MixedModels
    using cAIC: DofGLMM

    asscalar(x) = x isa AbstractArray ? only(x) : x

    fixture = joinpath(@__DIR__, "fixtures", "dof_glmm_poisson_level1.h5")
    @test isfile(fixture)

    h5open(fixture, "r") do f
        cases = filter(!=("meta"), keys(f))
        @test !isempty(cases)
        for name in cases
            g = f[name]
            haskey(g, "rho_ref") || error(
                "fixture case `$name` missing rho_ref — run generate_fixtures_glmm_poisson.R",
            )
            haskey(g, "raw_data") || error(
                "fixture case `$name` missing raw_data — run generate_fixtures_glmm_poisson.jl first",
            )

            rd = g["raw_data"]
            y_data = read(rd["y"])
            x_data = read(rd["x"])
            grp = read(rd["group"])

            dat = (; y=y_data, x=x_data, group=grp)
            m = fit(
                MixedModel, @formula(y ~ x + (1 | group)), dat, Poisson(); progress=false
            )

            ρ_ref = asscalar(read(g["rho_ref"]))
            ρ = DofGLMM.dof_glmm_poisson(m)

            # Level-2 tolerance: looser than Level-1 due to lme4/MixedModels.jl fit
            # discrepancy (to be recorded in DECISIONS.md once observed).
            @test ρ ≈ ρ_ref atol = 0.5
        end
    end
end
